### ISSUE TITLE
When does this extension support Firefox

### ISSUE THREAD

**Issue by jsvisa** [blocksecteam/metadock#1]

**Comment by yajin** [comment]
Thanks for your comment. Firefox support is in our roadmap. But we focus on Chrome in the next few releases.

Will let you know when it's ready for Firefox.

**Comment by cong1223** [comment]
MetaDock now supports Firefox. You can download it from our [website](https://blocksec.com/metadock) or the [Firefox Add-ons Marketplace](https://addons.mozilla.org/en-US/firefox/addon/metadock/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search).
