### ISSUE TITLE
New permissions policy for v4

### ISSUE THREAD

**Issue by xtc0r** [blocksecteam/metadock#13]
Why do you need allowance to read and change all sites for v4?

![image](https://github.com/blocksecteam/metadock/assets/36508484/62e434b6-eb3d-47b8-aa76-cbecd325acbb)

Why can't this be restricted to the supported websites?

![image](https://github.com/blocksecteam/metadock/assets/36508484/a00dd1c7-06df-495a-82cd-54ee8de2d1ea)

I feel very uncomfortable to allow an extension to read and change data on all sites.

![image](https://github.com/blocksecteam/metadock/assets/36508484/ae62ec5c-187d-4018-9f37-228bf6e8ef9d)

**Comment by cong1223** [comment]
Thanks for your feedback. We fully understand your concern about the new permissions of MetaDock. We make this choice to better serve our users and, at the same time only run MetaDock on specific websites.


First, we changed the mechanism to restrict the running sites from the Chrome permission system to the extension's internal configuration. All the websites are explicitly declared in the extension – and can be verified. This can make the extension less intrusive when supporting new chain browsers in the future.

Second, each website can be turned off in the MetaDock setting (Setting -> Supported website list). Only turn on the websites that you want.

Third, users can take the following methods if necessary.

a) MetaDock is open-sourced, and users can create his/her own Fork

b) Disable MetaDock by default and only enable it when necessary.

c) Create a new browser profile


We hope this can clarify your concern, and feel free to contact us if you have further questions.
