### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by infosec-us-team** [blocksecteam/metadock#4]
Amazing extension guys, congratulations, and thank you.

We have 2 questions.

1st- Calling the endpoint to download a zip `https://extension.blocksec.com//api/v1/source-code/download/?chain=arbitrum&address=0x73fe72c9caa0faf0e488570d5898984783e728df` we receive:
```
{"code":40000000,"message":"reach max daily quota limit"}
```
or
```
{"code":50000000,"message":"Internal Server Error","detail":"http status code: 429"}
```
How many requests per day include the max daily quota limit?

2nd- Can you guys please, open-source the code behind the endpoint `https://extension.blocksec.com//api/v1/source-code/download/` so we can run it locally, instead of spamming your endpoint from several IPs?

We're curious about how you took an address, and turn it into a directory tree with the source code of each dependency.

**Comment by cong1223** [comment]
Thank you for your support and feedback, but currently we do not support direct access to our API for users. Our daily quota for API requests is based on our internal throttling policy.
