### ISSUE TITLE
Any plan to support testnet

### ISSUE THREAD

**Issue by nzhl** [blocksecteam/metadock#6]
This tool is incredibly useful, and I regret not finding it earlier. Do we have any plans to support testnets like Goerli? Even if full functionality is not available, some support could be beneficial; for example:
1. query privivate variables
2. Show quick open in Dedaub for unverified contracts
3. Show quick open in DethCode for verified contracts

**Comment by cong1223** [comment]
Thanks,
MetaDock is open source, which means you can easily modify the code to support those test networks. The only feature that is temporarily not supported for the test networks is querying private variables.
