### ISSUE TITLE
download proxy implementation

### ISSUE THREAD

**Issue by arthurOmanko** [blocksecteam/metadock#7]
I want to download implementation contracts of proxy too at same time when downloading proxy contracts.
please support automatically downloading and directory ordering.

**Comment by MatrixA** [comment]
@arthurOmanko Good suggestion! I found MetaDock supports this feature recently. [Try here](https://etherscan.io/address/0xafc2f2d803479a2af3a72022d54cc0901a0ec0d6#code)

**Comment by cong1223** [comment]
Thank you for your suggestion. The feature is now supported.
