### ISSUE TITLE
Incorrect values reported for private variables

### ISSUE THREAD

**Issue by alxs** [blocksecteam/metadock#8]
There seems to be an issue with some of the additional private variables displayed on Etherscan. For example, [here](https://etherscan.io/address/0x729e04be8106c6bdef311ccf0b9636932f192867#readContract) Metadock reports that the `_initializing` variable is set to true, although it is false. `_initializing` is consistently misreported in Initializable contracts, but I assume this affects other variables as well.

**Comment by cong1223** [comment]
Thanks, it works now.
